### ISSUE TITLE
remove 5 DialogKeyboard from first start

### ISSUE THREAD

**Issue by Angelinas1** [AchillesPunks/Bingie.Mod.Matrix.Skin#1]
You have mess here, change "Skin.SetString" in "Skin.SetBool"
5 line is wrong

https://github.com/AchillesPunks/Bingie.Mod.Matrix.Skin/blob/main/xml/IncludesDefaultSkinSettings.xml#L81
https://github.com/AchillesPunks/Bingie.Mod.Matrix.Skin/blob/main/xml/IncludesDefaultSkinSettings.xml#L91
https://github.com/AchillesPunks/Bingie.Mod.Matrix.Skin/blob/main/xml/IncludesDefaultSkinSettings.xml#L94
https://github.com/AchillesPunks/Bingie.Mod.Matrix.Skin/blob/main/xml/IncludesDefaultSkinSettings.xml#L95
https://github.com/AchillesPunks/Bingie.Mod.Matrix.Skin/blob/main/xml/IncludesDefaultSkinSettings.xml#L107
This will remove ugly dialogs when start first time skin
@matke-84

**Comment by AchillesPunks** [comment]
Thanks my friend. ;-)
